//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptedBid
    {
        public AcceptedBid()
        {
            this.Services = new HashSet<Service>();
        }
    
        public System.Guid BidId { get; set; }
        public int OrderId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsCancelled { get; set; }
    
        public virtual Bid Bid { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual ICollection<Service> Services { get; set; }
    }
}
