//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.AdditionalInfoRequests = new HashSet<AdditionalInfoRequest>();
            this.AdditionalInfos = new HashSet<AdditionalInfo>();
            this.Bids = new HashSet<Bid>();
        }
    
        public System.Guid Id { get; set; }
        public int OrderId { get; set; }
        public string Description { get; set; }
        public System.Guid TagId { get; set; }
        public System.DateTime ServiceDue { get; set; }
        public System.DateTime BiddingCompletionDate { get; set; }
        public string Reference { get; set; }
        public int LocationId { get; set; }
        public System.Guid ClientId { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual ICollection<AdditionalInfoRequest> AdditionalInfoRequests { get; set; }
        public virtual ICollection<AdditionalInfo> AdditionalInfos { get; set; }
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual Client Client { get; set; }
        public virtual Location Location { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
