//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHub.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public ServiceProvider()
        {
            this.AdditionalInfoRequests = new HashSet<AdditionalInfoRequest>();
            this.AdditionalInfos = new HashSet<AdditionalInfo>();
            this.Bids = new HashSet<Bid>();
            this.Ratings = new HashSet<Rating>();
            this.Locations = new HashSet<Location>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContactNumber { get; set; }
        public string About { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual ICollection<AdditionalInfoRequest> AdditionalInfoRequests { get; set; }
        public virtual ICollection<AdditionalInfo> AdditionalInfos { get; set; }
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
