//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonoMight.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AnonoMightEntities : DbContext
    {
        public AnonoMightEntities()
            : base("name=AnonoMightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<Definition> Definitions { get; set; }
        public virtual DbSet<FacebookProfile> FacebookProfiles { get; set; }
        public virtual DbSet<ImagePost> ImagePosts { get; set; }
        public virtual DbSet<Tweet> Tweets { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    
        public virtual int CreateDefinitionsTable(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateDefinitionsTable", tableNameParameter);
        }
    
        public virtual int CreateFacebookProfilesTable(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateFacebookProfilesTable", tableNameParameter);
        }
    
        public virtual int CreateImagePostsTable(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateImagePostsTable", tableNameParameter);
        }
    
        public virtual int CreateTweetsTable(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateTweetsTable", tableNameParameter);
        }
    
        public virtual int GetTopFacebookLink(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetTopFacebookLink", tableNameParameter);
        }
    
        public virtual ObjectResult<FacebookProfile> GetTopFacebookLinkForTheLastMonth(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacebookProfile>("GetTopFacebookLinkForTheLastMonth", tableNameParameter);
        }
    
        public virtual ObjectResult<FacebookProfile> GetTopFacebookLinkForTheLastMonth(string tableName, MergeOption mergeOption)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacebookProfile>("GetTopFacebookLinkForTheLastMonth", mergeOption, tableNameParameter);
        }
    }
}
