//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonoMight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Definition
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int Reports { get; set; }
    }
}
