//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonoMight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public System.Guid Id { get; set; }
        public byte ReportClass { get; set; }
        public string SiteName { get; set; }
        public System.Guid PostId { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
