//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonoMight.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public System.Guid Id { get; set; }
        public string SiteName { get; set; }
        public string SiteTitle { get; set; }
        public byte SiteType { get; set; }
        public byte[] SiteLogo { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
    }
}
